export const ON_POST_CREATE_START = "ON_POST_CREATE_START";
export const ON_POST_CREATE_SUCCESS = "ON_POST_CREATE_SUCCESS";
export const ON_POST_CREATE_FAIL = "ON_POST_CREATE_FAIL";

export const ON_POST_FINDALLPOST_START = "ON_POST_FINDALLPOST_START";
export const ON_POST_FINDALLPOST_SUCCESS = "ON_POST_FINDALLPOST_SUCCESS";
export const ON_POST_FINDALLPOST_FAILED = "ON_POST_FINDALLPOST_FAILED";

export const ON_POST_FINDPOSTOTHER_START = "ON_POST_FINDPOSTOTHER_START";
export const ON_POST_FINDPOSTOTHER_SUCCESS = "ON_POST_FINDPOSTOTHER_SUCCESS";
export const ON_POST_FINDPOSTOTHER_FAILED = "ON_POST_FINDPOSTOTHER_FAILED";
