export const ON_USERFINDALL_START = "ON_USERFINDALL_START";
export const ON_USERFINDALL_SUCCESS = "ON_USERFINDALL_SUCCESS";
export const ON_USERFINDALL_FAILED = "ON_USERFINDALL_FAILED";

export const ON_USERFINDBYID_START = "ON_USERFINDBYID_START";
export const ON_USERFINDBYID_SUCCESS = "ON_USERFINDBYID_SUCCESS";
export const ON_USERFINDBYID_FAILED = "ON_USERFINDBYID_FAILED";

