export const FUZY_BAD_REQUEST = "FUZY_BAD_REQUEST";
export const FUZY_UNAUTHORIZED_ERROR = "FUZY_UNAUTHORIZED_ERROR";
export const FUZY_404_NOT_FOUND = "FUZY_404_NOT_FOUND";
export const FUZY_INTERNAL_SERVER_ERROR = "FUZY_INTERNAL_SERVER_ERROR";
export const FUZY_UNKNOWN_ERROR = "FUZY_UNKNOWN_ERROR";
export const FUZY_NETWORK_ERROR = "FUZY_NETWORK_ERROR";
export const FUZY_OTHER_ERROR = "FUZY_OTHER_ERROR";
